### PR TITLE
Change backend structure to MVC

### PR DESCRIPTION
**Pull request by HsinI65018**
Hello teacher~I'm 張心怡.
I've done with back-end MVC structure, if there is nothing wrong, I'll keep dealing with front-end MVC structure.
Thank you.

### CODE REVIEW

**Comment by HsinI65018** [comment]
I've done with front-end MVC structure too!
But I'm not really sure about that, cause there are few parts that I think its weird...

First, I create these two function, I think it doesn't really makes sense, but if I leave them in the init function, the init function looks too big, so I'm curious is that ok to code like this?

截圖 2022-03-16 下午9 03 49
截圖 2022-03-16 下午9 04 20

Second, my start point is fetchAPI not init function, is that ok too?

By the way, I found some bug in my previous code, only in this url (http://18.142.100.126:3000/attraction/6) that my 輪播 logic is not working, but I fixed it, I just didn't git pull it yet.
Just let you know before I do any further action.Thank you

**Comment by cwpeng** [comment]
I think you do a good job. Of course, there is always something to improve. We can do more conversation online directly.

**Comment by HsinI65018** [comment]
Hello, teacher~I've updated new structure for back-end MVC, and my structure is base on the picture below.
In the future, my controller file, model file and view file will have other three files below, and they are base on the Taipei trip API develop file's four topic.
Thank you.

截圖 2022-03-17 下午6 33 53

**Comment by HsinI65018** [comment]
Hello, teacher~I've updated front-end MVC structure, and created a package called **createDivElement.js** to help me create multiple divs, hope the idea is kind of similiar with teacher's  .
And I think my MVC structure is done for now, but I still willing to get some recommendations from teacher, and I'll try to figure it out in the future.
Thank you.

**Comment by cwpeng** [comment]
Interesting implementation. Follow your idea, I think class name DivElement will be better than createDivElement. We are used to use a noun for class name, not a verb.

**Comment by HsinI65018** [comment]
I've changed the name, but I still got some questions to ask...

I've felt confused about my controller and view, and these picture are from my POST API (/api/user).

 I thought my controller is not that good to understand at the first time, cause some of my logic write in view, so my controller seem lose some connection, and I think maybe I should write like the model, one return in one def, but If I change the structure I also think this look kind of weird and pointless, and my controller will be large again, so I'm not sure what to do...Is it ok for my view to code like this? 😂

controller
model
view

**Pull request closed without merging**
