### PR TITLE
week3 first pull request

### PR DESCRIPTION
**Pull request by HsinI65018**
Hello teacher, I'm 張心怡.

These are my testing url.
http://18.142.100.126:3000/
http://18.142.100.126:3000/attraction/5

After merging the homework I'll deal with MVC, and ask for pull request again, thank you.

### CODE REVIEW

**Comment by HsinI65018** [comment]
I closed the PR because I found out that If the url open in safari, the font-family is not correct, but if I open it again in Chrome , the font-family is correct.
That gave me a damn shock...

**Comment by cwpeng** [comment]
Font-Family is OK. I think it's not critical part. But I think the title style of 景點地址 and 交通方式 should align with design.

**Comment by HsinI65018** [comment]
oh...I didn't notice, but I fixed it immediately haha~

These are 'new' testing url.
http://18.142.100.126:3000/
http://18.142.100.126:3000/attraction/5

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
