### PR TITLE
API on AWS finally!!!

### PR DESCRIPTION
**Pull request by HsinI65018**
老師好～我是張心怡，discord 是 Hsin-I

http://18.142.100.126:3000/api/attractions?page=1
http://18.142.100.126:3000/api/attractions?page=0&keyword=藝術
http://18.142.100.126:3000/api/attraction/100

### CODE REVIEW

**Comment by cwpeng** [comment]
Add me as reviewer, not assignee, if you want me to review your task.

**Comment by HsinI65018** [comment]
老師不好意思我又看錯了 😅

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But we should prevent select all data from table at once. Use LIMIT statement in SQL query is best practice for range selection. I mean you should use LIMIT in this query `get_db("SELECT id,name,category,description,address,transport,mrt,latitude,longitude,images FROM attractions WHERE name LIKE %s", ['%'+keyword+'%'], 'all')` and modify any related code necessary.

Fix it, create new commit, and ask me to review again.

**Comment by HsinI65018** [comment]
OK. I got it.
 I'll fix it tomorrow and ask for review again, thank you teacher.

**Comment by HsinI65018** [comment]
Hi, teacher.
I fixed the SQL statement which had advised yesterday.
If there is any recommendations please let me know, thank you.

**Comment by cwpeng** [comment]
Try to ask me review again from right side of this page.

**Comment by HsinI65018** [comment]
ok. I add the reviewer again.

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Pull request merged**
